apiVersion: v1
kind: Service
metadata:
  name: authserver
  labels:
    app: authserver
spec:
  type: NodePort
  ports:
  - port: 8085
    nodePort: 30085
    protocol: TCP
  selector:
    app: authserver-pods
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver-pods
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: authserver-pods
    spec:
      containers:
      - name: authserver
        image: ivanarandjelovic/auth-server:v0.0.5-SNAPSHOT
        ports:
        - containerPort: 8085
        resources:
          requests:
            memory: 300Mi
#            cpu: 1000m
          limits:
            memory: 1000Mi
#            cpu: 500m

