kind: ConfigMap
apiVersion: v1
metadata:
  name: service-a
data:
  service-a.testProperty: test1value
  service-a.service1Url: http://service1:8081/service1
  security.oauth2.resource.user-info-uri: http://authserver:8085/authserver/user
  spring.zipkin.baseUrl: http://zipkin:9411/
  # Limiting smapling on top service is sufficient
  #spring.sleuth.sampler.probability: "0.1"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: service1
data:
  security.oauth2.resource.user-info-uri: http://authserver:8085/authserver/user
  spring.zipkin.baseUrl: http://zipkin:9411/
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authserver
data:
  spring.zipkin.baseUrl: http://zipkin:9411/
  spring.datasource.url: jdbc:p6spy:h2:tcp://h2:1521/./test
  #logging.level.root: DEBUG
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: objekti
data:
  spring.zipkin.baseUrl: http://zipkin:9411/
  spring.datasource.url: jdbc:p6spy:h2:tcp://h2:1521/./objekti
  #logging.level.root: DEBUG