apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    name: serving
    nodePort: 30200
    protocol: TCP
  - port: 9300
    name: node-to-node
    nodePort: 30300
    protocol: TCP
  selector:
    app: elasticsearch-pods
---    
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: elastic-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "C:\\data\\elasticsearch"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: elastic-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-pods
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: elasticsearch-pods
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
        ports:
        - containerPort: 9200
          name: port1
        - containerPort: 9300
          name: port2
#        resources:
#          limits:
#            memory: 2Gi
#            cpu: 500m
#          requests:
#            memory: 1Gi
#            cpu: 100m
        env:
          # NOTE: the cluster name; update this
          - name: cluster.name
            value: elasticsearch-cloud1
#        env:
#        - name: "NETWORK_HOST"
#          value: "_site_,_lo_"
#        env:
#        - name: JAVA_OPTS
#          value: "-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG"
#        volumeMounts:
#        - mountPath: "/usr/share/elasticsearch/data"
#          name: elastic-pv-storage
#      volumes:
#      - name: elastic-pv-storage
#        persistentVolumeClaim:
#          claimName: elastic-pv-claim
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: host-elasticsearch 
      volumes:
        - name: host-elasticsearch
          hostPath:
            path: /C/data/elasticsearch
            type: Directory
