apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: front-pods
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-pods
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: front-pods
    spec:
      containers:
      - name: front
        image: ivanarandjelovic/front:v0.0.5-SNAPSHOT
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 5Mi
#            cpu: 1000m
          limits:
            memory: 10Mi
#            cpu: 500m
