apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: servicea
          servicePort: 8082
      - path: /
        backend:
          serviceName: front
          servicePort: 80