apiVersion: v1
kind: Service
metadata:
  name: servicea
  labels:
    app: servicea
spec:
  type: NodePort
  ports:
  - port: 8083
    nodePort: 30003
    protocol: TCP
  selector:
    app: servicea-pods
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea-pods
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: servicea-pods
    spec:
      containers:
      - name: servicea
        image: ivanarandjelovic/service-a:v0.0.5-SNAPSHOT
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: 300Mi
#            cpu: 1000m
          limits:
            memory: 800Mi
#            cpu: 500m

