apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
  - port: 9411
    nodePort: 30411
    protocol: TCP
  selector:
    app: zipkin-pods
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-pods
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: zipkin-pods
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
#        env:
#        - name: JAVA_OPTS
#          value: -Xmx32m
        ports:
        - containerPort: 9411
        resources:
          requests:
            memory: 100Mi
#            cpu: 100m
          limits:
            memory: 600Mi
#            cpu: 500m
#        env:
#        - name: JAVA_OPTS
#          value: "-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG"
